const SERVER_IP='http://94.237.96.118'
const API = 'http://94.237.96.118/api/'
const BACKEND_LOGIN = 'login/'
const BACKEND_REFRESH = 'refresh/'
const BACKEND_REGISTER = 'register/'
const BACKEND_UPLOAD_FILE = 'upload/'
const BACKEND_REPORT_POST = 'reports/'
const BACKEND_ALL_REPORTS='reports/all/'
const BACKEND_ALL_REPORTS_VIA_USERNAME='reports/'
const BACKEND_SUBSCRIBED_REPORTS='reports/subs/'
const SEARCH_ENDPOINT='search/'
const BACKEND_LIKE='like/'
const BACKEND_PROFILE='profile/'


export default {
    API,
    SERVER_IP,
    BACKEND_REFRESH,
    BACKEND_REGISTER,
    BACKEND_LOGIN,
    BACKEND_UPLOAD_FILE,
    BACKEND_REPORT_POST,
    BACKEND_ALL_REPORTS,
    BACKEND_ALL_REPORTS_VIA_USERNAME,
    BACKEND_SUBSCRIBED_REPORTS,
    SEARCH_ENDPOINT,
    BACKEND_LIKE,
    BACKEND_PROFILE,

}
