version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django:
    image: python:3.8
    container_name: bm1_django
    depends_on:
      - postgres
    volumes:
      - .:/app
      - ./static:/static
    working_dir: /app
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: bash -c "pip install -r requirements.txt &&
      python manage.py makemigrations &&
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      gunicorn -w 4 -t 180 -b 0.0.0.0:8000 bulletin599.wsgi"

  postgres:
    image: postgres:12
    container_name: bm1_postgres
    env_file:
      - .env
  
